### PR TITLE
Replaces print with logging (fixes #50)

### LINKED ISSUE #50: Use logging module instead of print
Currently there are various random print function calls. For example: https://github.com/coin-or/python-mip/blob/a836a7198dc0e4b08e15d92f11f26039f2ebff96/mip/model.py#L1277 
It would be great if it could be migrated to some logging module (i.e. https://docs.python.org/3/library/logging.html) so that package output could be managed/configured/suppressed easily.

### PR DESCRIPTION
**Pull request by amarvin**

### CODE REVIEW

**Comment by amarvin** [comment]
Disables print messages by default, but allows users to control logging after `import mip`. This approach is adopted from the best practice in `requests` (https://github.com/psf/requests/blob/master/requests/__init__.py).

Might want to add documentation to say the root logger of the module is named "mip", and how to change logging level and output (e.g. stdout, file).

**Comment by sebheger** [comment]
@amarvin Could something from here be "rescued" to the latest master? Or can this PR be closed?

**Comment by sebheger** [comment]
Closed, as it seems that there is nothing to be rescued here as outdated.

**Comment by amarvin** [comment]
This PR should be closed, but it's unfortunate that @uurriola didn't just build off this PR and instead did !86 on the same topic three months after my PR was opened. Not sure if there were differences between my work or his later work.

**Pull request closed without merging**
