### PR TITLE
WIP: Use relative imports

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by h-g-s** [comment]
Hi,  one motivation for the use of ugly  "mip.Var" in typing was the documentation (sphinx, sphinx-autodoc-typehints),  they only generated correct, cross-referenced documentation for types using the more verbose typing definition. Could you generate the documentation in your machine and check if it now works ?

**Comment by lpsinger** [comment]
@h-g-s, I'm working on it. Please treat this as work in progress (hence WIP); I only pushed it so that I could see the CI checks.

The rationale for this PR is that it should eventually fix some errors due to circular imports that I noticed when requesting a specific solver (e.g. `Model(solver=CBC)`).

**Comment by h-g-s** [comment]
ok !

**Comment by lpsinger** [comment]
Closing in favor of #155.

**Pull request closed without merging**
