### PR TITLE
Use setuptools_scm to determine the version

### PR DESCRIPTION
**Pull request by lpsinger**
This fixes an issue where cffi was required to build a wheel:

    $ python setup.py bdist_wheel
    Traceback (most recent call last):
      File "setup.py", line 6, in <module>
        exec(open("mip/constants.py").read(), version_dict)
      File "<string>", line 4, in <module>
    ModuleNotFoundError: No module named 'cffi'

It should also streamline the process of making a release a tiny bit.

### CODE REVIEW

**Comment by h-g-s** [comment]
Hi @lpsinger , sorry my ignorance,  how do I inform the version with setuptools_scm , i.e., before releasing a new version ?

**Comment by lpsinger** [comment]
Just create a git tag. When you build your release (with `python setup.py bdist_wheel`, `pip wheel`, or whatever you do), setuptools_scm will detect the tag and use that as the version.

**Comment by lpsinger** [comment]
Any update on this? The false cffi build-time dependency is causing some installation issues with certain virtual environment tools (e.g. poetry).

**Comment by lpsinger** [comment]
Thank you!

**Comment by h-g-s** [comment]
Hi @lpsinger , just tagged version 1.13.0 ,  the version appears as

1.13.1.dev0+gc7c8d6b.d20201122

Could this string be trimmed ?    Or it is a good practice to include these additional details ?  (for me they do not seem to be relevant) 

Cheers

**Comment by h-g-s** [comment]
Ops, the problem is bigger than I though,   the string is not accepted as a valid version

HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
'1.13.1.dev0+gc7c8d6b.d20201122' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for more information.

**Comment by lpsinger** [comment]
> 1.13.1.dev0+gc7c8d6b.d20201122

It looks like you made a tarball before tagging.

**Comment by h-g-s** [comment]
worked, thanks !

**Pull request merged**
